---
name: Run Gradle PR
on: [pull_request]
permissions: read-all
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    
    - name: Setup Node
      uses: actions/setup-node@master
    
    - name: Install node modules
      run: |
        npm install
    - name: Build with Gatsby
      env:
          GATSBY_PORTFOLIO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run build
