---
name: Run Gradle PR
on: [pull_request]
permissions: read-all
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
    
    - name: Setup Node
      uses: actions/setup-node@master
    
    - name: Install node modules
      run: |
        npm install

    - name: Build
      run: |
        npm build
